### ISSUE TITLE
Un dataset con i dati regionali alla data odierna

### ISSUE THREAD

**Issue by cirospat** [DavideMagno/ItalianCovidData#1]
Ciao @DavideMagno 
innanzitutto grazie di aver creato questo repo. **Utile per fare analisi e riusi**. Complimenti. 

Appena ho consultato il contenuto dei due file tabellari, ho pensato che un file specifico potrebbe essere quello della sola situazione finale dei dati. Sicuramente a molte persone, oltre ai 2 dataset creati, servirà questo dei dati ultimi delle regioni.
Sicuramente si potrà fare applicando ad uno dei due una formula che estrae i dati ultimi per regione.
Ovviamente se condividi l'utilità di tale dataset. 
Rinnovo i miei complimenti per questo repo che in verità mancava in Italia. 
Saluti e grazie. 
Ciro

**Comment by DavideMagno** [comment]
Ciao Ciro - grazie della domanda.
Il calcolo del totale dei casi è abbastanza un caso aperto: c'è chi include i guariti/morti e chi no. 

Per questo motivo non ho inserito quella colonna ed ho lasciato ai fruitori del dato la possibilità di calcolarlo secondo i loro criteri. 

Detto questo, probabilmente aggiungerò a breve un file con i dati provinciali e in quel caso aggiungerò anche il totale regionale secondo i criteri utilizzati dalla Protezione Civile.

Grazie ancora,
Davide
