### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [DavideMagno/ItalianCovidData#2]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the OpenSourceWuhan page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/OpenSourceWuhan/world

Cheers!

**Comment by DavideMagno** [comment]
Thanks a lot! I do agree with you: open source helps. We are big community in the world...and on GitHub!

Looking forward to see more and more data on your amazing aggregator.

Cheers!

**Comment by DavideMagno** [comment]
@WeileiZeng there is finally a repo with the data from Italian officials. You can find it here: https://github.com/pcm-dpc/COVID-19

**Comment by WeileiZeng** [comment]
Thanks! Added as well.
