### ISSUE TITLE
Grazie

### ISSUE THREAD

**Issue by dariosalvi78** [DavideMagno/ItalianCovidData#3]
Hello Davide, I just wanted to let you know that we are using your data to populate this database we are building: https://covid19db.github.io/

I hope you can keep updating your data, it's making a difference!

**Comment by DavideMagno** [comment]
Hi Dario, I am honoured you are using my repo for your dB. As long as there will be official data, the repo will be updated accordingly.

Just one thing: my actual surname is Magno (I see Mango on the website 😉)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dariosalvi78** [comment]
Ops, I'll correct that!
grazie mille!
